project:
  name: "dna-metabolism-ml-prostate"
  seed: 123
  out_dir: "results"

tcga:
  project: "TCGA-PRAD"
  workflow: "HTSeq - Counts"

deg:
  fdr: 0.01
  fc: 1.5

clustering:
  max_k: 6
  reps: 1000
  p_item: 0.8
  p_feature: 0.8
  k_selected: 2

survival:
  endpoint: "PFI"        # change to OS/DFS/PFI as needed
  test_size: 0.3
